export const ALL_REPORT_REQUEST = "ALL_REPORT_REQUEST";
export const ALL_REPORT_SUCCESS = "ALL_REPORT_SUCCESS";
export const ALL_REPORT_FAIL = "ALL_REPORT_FAIL";

export const ADMIN_REPORT_REQUEST = "ADMIN_REPORT_REQUEST";
export const ADMIN_REPORT_SUCCESS = "ADMIN_REPORT_SUCCESS";
export const ADMIN_REPORT_FAIL = "ADMIN_REPORT_FAIL";

export const USER_REPORT_REQUEST = "USER_REPORT_REQUEST";
export const USER_REPORT_SUCCESS = "USER_REPORT_SUCCESS";
export const USER_REPORT_FAIL = "USER_REPORT_FAIL";

export const NEW_REPORT_REQUEST = "NEW_REPORT_REQUEST";
export const NEW_REPORT_SUCCESS = "NEW_REPORT_SUCCESS";
export const NEW_REPORT_RESET = "NEW_REPORT_RESET";
export const NEW_REPORT_FAIL = "NEW_REPORT_FAIL";

export const UPDATE_REPORT_REQUEST = "UPDATE_REPORT_REQUEST";
export const UPDATE_REPORT_SUCCESS = "UPDATE_REPORT_SUCCESS";
export const UPDATE_REPORT_RESET = "UPDATE_REPORT_RESET";
export const UPDATE_REPORT_FAIL = "UPDATE_REPORT_FAIL";

export const DELETE_REPORT_REQUEST = "DELETE_REPORT_REQUEST";
export const DELETE_REPORT_SUCCESS = "DELETE_REPORT_SUCCESS";
export const DELETE_REPORT_RESET = "DELETE_REPORT_RESET";
export const DELETE_REPORT_FAIL = "DELETE_REPORT_FAIL";

export const REPORT_DETAILS_REQUEST = "REPORT_DETAILS_REQUEST";
export const REPORT_DETAILS_SUCCESS = "REPORT_DETAILS_SUCCESS";
export const REPORT_DETAILS_FAIL = "REPORT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";