export const CREATE_TREAT_REQUEST = "CREATE_TREAT_REQUEST";
export const CREATE_TREAT_SUCCESS = "CREATE_TREAT_SUCCESS";
export const CREATE_TREAT_FAIL = "CREATE_TREAT_FAIL";

export const MY_TREATS_REQUEST = "MY_TREATS_REQUEST";
export const MY_TREATS_SUCCESS = "MY_TREATS_SUCCESS";
export const MY_TREATS_FAIL = "MY_TREATS_FAIL";

export const REPORT_TREATS_REQUEST = "REPORT_TREATS_REQUEST";
export const REPORT_TREATS_SUCCESS = "REPORT_TREATS_SUCCESS";
export const REPORT_TREATS_FAIL = "REPORT_TREATS_FAIL";

export const ALL_TREATS_REQUEST = "ALL_TREATS_REQUEST";
export const ALL_TREATS_SUCCESS = "ALL_TREATS_SUCCESS";
export const ALL_TREATS_FAIL = "ALL_TREATS_FAIL";

export const UPDATE_TREAT_REQUEST = "UPDATE_TREAT_REQUEST";
export const UPDATE_TREAT_SUCCESS = "UPDATE_TREAT_SUCCESS";
export const UPDATE_TREAT_RESET = "UPDATE_TREAT_RESET";
export const UPDATE_TREAT_FAIL = "UPDATE_TREAT_FAIL";

export const DELETE_TREAT_REQUEST = "DELETE_TREAT_REQUEST";
export const DELETE_TREAT_SUCCESS = "DELETE_TREAT_SUCCESS";
export const DELETE_TREAT_RESET = "DELETE_TREAT_RESET";
export const DELETE_TREAT_FAIL = "DELETE_TREAT_FAIL";

export const TREAT_DETAILS_REQUEST = "TREAT_DETAILS_REQUEST";
export const TREAT_DETAILS_SUCCESS = "TREAT_DETAILS_SUCCESS";
export const TREAT_DETAILS_FAIL = "TREAT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";